# TASK NO 24
# PYTHOM PROGRAM TO CALCULATE SUM OF FIRST N POSITIVE INTEGER NUMBERS:
n = int(input("ENTER AN INTEGER:"))
sum1 = 0
for i in range(1,n+1):
    sum1 += i
print("THE SUM OF FIRST N POSITIVE INTEGERS:",sum1)    