#TASK NO 3
#PYTHON PROGRAM TO CHECK WHETHE A NO. IS DIVISIBLE BY ANOTHER NUMBER!
num_1 = int(input("PLEASE ENTER FIRST INTEGER NUMBER ="))
num_2 = int(input("PLEASE ENTER SECOND INTEGER NUMBER ="))
if num_1 % num_2 == 0:
    print("COMPLETELY DIVISIBLE!")
else:
    print("NOT COMPLETELY DIVISIBLE!") 

